### ISSUE TITLE
Test defined in cljx files are not recognized

### ISSUE THREAD

**Issue by jeluard** [adzerk/boot-test#3]
Test defined in cljx files and processed via [boot-cljx](https://github.com/Deraen/boot-cljx) are not recognized by `boot-test`.
Combination of both tasks also increases the processing time: 10 seconds instead of less than a second if I remove the `test` task (but still keep the `cljx` task).

**Comment by jeluard** [comment]
Doing some more tests I cannot reproduce this.

**Comment by alandipert** [comment]
Thanks anyway for reporting, if you do end up reproducing I'll be happy to investigate.
