### ISSUE TITLE
Does not find any tests

### ISSUE THREAD

**Issue by nblumoe** [adzerk/boot-test#4]
I got tests in "/tests" and added that to the source-paths like indicated in the README. I also tried having test in the applications source files directly. However, `boot test` does not run any tests, it just exits with `No namespaces were tested.`

I think namespaces need to be passed as parameters in any case? How would the given example `boot watch test` from the README work?

If one has to provide the namespaces as params, what would be a reasonable way to do so without having to put the relevant namespaces from tests into the task definition?

Help is highly appreciated, I feel like I am missing something here, shouldn't be that hard to get this working, right?

**Comment by nblumoe** [comment]
Seems like I found a minimal example in boot-test itself:
```clojure
(task-options!
 pom  {:project     'adzerk/boot-test
       :version     +version+
       :description "Run some tests in boot!"
       :url         "https://github.com/adzerk/boot-test"
       :scm         {:url "https://github.com/adzerk/boot-test"}
       :license     {:name "Eclipse Public License"
                     :url  "http://www.eclipse.org/legal/epl-v10.html"}}
 test {:namespaces '#{adzerk.boot-test.test}})
```
https://github.com/adzerk/boot-test/blob/master/build.boot#L22

This way I can make it work, great! Remaining issue: Is there an obvious way how to automatically get all the namespaces from files in the "test" directory in there? Had a look at filesets but not sure if that's the way to go.

**Comment by micha** [comment]
Bam! Enjoy :)

**Comment by nblumoe** [comment]
Amazing, thanks! :+1:

**Comment by daveyarwood** [comment]
Just noticed this and it's awesome. Thx @micha ! :saxophone:
